Repository vecosystem/VECO_Backend, pull requests merged in 2025-08, with the labels that each got.

#58 ✨ [Feat] 목표 후순위 API 개발
  application.log
  src/main/java/com/example/Veco/domain/goal/controller/GoalController.java
  src/main/java/com/example/Veco/domain/goal/dto/request/GoalReqDTO.java
  src/main/java/com/example/Veco/domain/goal/entity/Goal.java
  src/main/java/com/example/Veco/domain/goal/exception/code/GoalErrorCode.java
  src/main/java/com/example/Veco/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalCommandService.java
  src/main/java/com/example/Veco/domain/goal/service/query/GoalQueryService.java
Labels: ✨Feat

#64 Feat/#47 이슈 생성 이름조회 api
  src/main/java/com/example/Veco/domain/issue/controller/IssueController.java
  src/main/java/com/example/Veco/domain/issue/converter/IssueConverter.java
  src/main/java/com/example/Veco/domain/issue/dto/IssueReqDTO.java
  src/main/java/com/example/Veco/domain/issue/dto/IssueResponseDTO.java
  src/main/java/com/example/Veco/domain/issue/exception/code/IssueSuccessCode.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
  src/main/java/com/example/Veco/domain/issue/service/command/IssueCommandService.java
  src/main/java/com/example/Veco/domain/issue/service/command/IssueCommandServiceImpl.java
  src/main/java/com/example/Veco/domain/issue/service/command/IssueTransactionalService.java
  src/main/java/com/example/Veco/domain/notification/controller/NotiController.java
  src/main/java/com/example/Veco/domain/team/entity/Team.java
Labels: ✨Feat

#70 🔨 fix: 알림 예외처리 수정
  src/main/java/com/example/Veco/domain/memberNotification/exception/code/MemberNotiErrorCode.java
  src/main/java/com/example/Veco/domain/memberNotification/service/MemberNotiCommandServiceImpl.java
Labels: 🐛 Bug & Fix

#66 Fix/#62 외부 이슈 CRUD 관련 에러 수정
  deployment-fixes.md
  src/main/java/com/example/Veco/domain/external/converter/ExternalConverter.java
  src/main/java/com/example/Veco/domain/external/entity/External.java
  src/main/java/com/example/Veco/domain/external/service/ExternalService.java
Labels: 🐛 Bug & Fix

#86 ✨ [Feat] 워크스페이스 연동 해제 API 구현
  src/main/java/com/example/Veco/domain/assignee/entity/Assignee.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeRepository.java
  src/main/java/com/example/Veco/domain/mapping/repository/MemberTeamRepository.java
  src/main/java/com/example/Veco/domain/workspace/controller/WorkspaceRestController.java
  src/main/java/com/example/Veco/domain/workspace/service/WorkspaceCommandService.java
  src/main/java/com/example/Veco/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: ✨Feat

#84 ✨ [Feat] 카카오 OAuth2 로그인 구현
  src/main/java/com/example/Veco/global/auth/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/example/Veco/global/auth/oauth2/util/OAuth2Util.java
  src/main/resources/static/login-test.html
Labels: ✨Feat

#91 🔨 fix: 팀에 이슈가 없을 때의 응답 수정
  src/main/java/com/example/Veco/domain/issue/controller/IssueController.java
  src/main/java/com/example/Veco/domain/issue/repository/CustomIssueRepositoryImpl.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
Labels: 🐛 Bug & Fix

#97 Feat:#96 GitHub 연동 플로우 수정, 프론트엔드로 리다이렉트
  src/main/java/com/example/Veco/domain/external/controller/ExternalController.java
  src/main/java/com/example/Veco/domain/external/controller/ExternalSwaggerDocs.java
  src/main/java/com/example/Veco/domain/external/controller/GitHubRestController.java
  src/main/java/com/example/Veco/domain/external/controller/GitHubSwaggerDocs.java
  src/main/java/com/example/Veco/domain/external/controller/GitHubWebhookController.java
  src/main/java/com/example/Veco/domain/external/converter/ExternalConverter.java
  src/main/java/com/example/Veco/domain/external/dto/GitHubPullRequestPayload.java
  src/main/java/com/example/Veco/domain/external/dto/IssueCommentWebhookDTO.java
  src/main/java/com/example/Veco/domain/external/entity/External.java
  src/main/java/com/example/Veco/domain/external/service/ExternalService.java
  src/main/java/com/example/Veco/domain/external/service/GitHubIssueCommentService.java
  src/main/java/com/example/Veco/domain/external/service/GitHubIssueService.java
  src/main/java/com/example/Veco/domain/external/service/GitHubPullRequestService.java
  src/main/java/com/example/Veco/domain/external/service/GitHubService.java
Labels: ✨Feat

#101 Feat/#93 워크스페이스 전용 팀 생성
  src/main/java/com/example/Veco/domain/member/service/MemberCommandService.java
  src/main/java/com/example/Veco/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/Veco/domain/profile/entity/Profile.java
  src/main/java/com/example/Veco/domain/team/entity/Team.java
  src/main/java/com/example/Veco/domain/team/repository/TeamRepository.java
  src/main/java/com/example/Veco/domain/workspace/controller/SettingRestController.java
  src/main/java/com/example/Veco/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/example/Veco/domain/workspace/dto/WorkspaceResponseDTO.java
  src/main/java/com/example/Veco/domain/workspace/entity/WorkSpace.java
  src/main/java/com/example/Veco/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: ✨Feat

#104 🔨 [fix] 이슈 전체 조회 시의 조회 순서 수정
  src/main/java/com/example/Veco/domain/issue/controller/IssueController.java
  src/main/java/com/example/Veco/domain/issue/exception/code/IssueErrorCode.java
  src/main/java/com/example/Veco/domain/issue/repository/CustomIssueRepository.java
  src/main/java/com/example/Veco/domain/issue/repository/CustomIssueRepositoryImpl.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
Labels: 🐛 Bug & Fix

#106 ♻️ [Refactor] 담당자가 없는 경우도 필터에 포함
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeRepository.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalTransactionalService.java
  src/main/java/com/example/Veco/domain/goal/service/query/GoalQueryService.java
Labels: ♻️ Refactor, ✨Feat

#109 🔨 [fix] '매니저 없음' 필터에 대한 이슈 조회 오류 수정
  src/main/java/com/example/Veco/domain/issue/controller/IssueController.java
  src/main/java/com/example/Veco/domain/issue/dto/IssueResponseDTO.java
  src/main/java/com/example/Veco/domain/issue/repository/CustomIssueRepositoryImpl.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
Labels: 🐛 Bug & Fix

#112 ✨ [Feat] 목표 제약 조건 설정
  src/main/java/com/example/Veco/domain/goal/controller/GoalController.java
  src/main/java/com/example/Veco/domain/goal/dto/request/GoalReqDTO.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalCommandService.java
  src/main/java/com/example/Veco/domain/goal/service/query/GoalQueryService.java
  src/main/java/com/example/Veco/domain/mapping/repository/MemberTeamRepository.java
  src/main/java/com/example/Veco/global/apiPayload/code/ErrorStatus.java
  src/main/java/com/example/Veco/global/apiPayload/exception/ExceptionAdvice.java
Labels: ♻️ Refactor, ✨Feat

#116 ♻️ [Refactor] 목표 생성 수정 조회 시작일 null 가능
  src/main/java/com/example/Veco/domain/goal/controller/GoalController.java
  src/main/java/com/example/Veco/domain/goal/converter/GoalConverter.java
  src/main/java/com/example/Veco/domain/goal/dto/request/GoalReqDTO.java
  src/main/java/com/example/Veco/domain/goal/dto/response/GoalResDTO.java
  src/main/java/com/example/Veco/domain/goal/exception/code/GoalErrorCode.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalCommandService.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalTransactionalService.java
Labels: ♻️ Refactor

#122 ✨ [Feat] 회원 탈퇴 api 구현
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDsl.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDslImpl.java
  src/main/java/com/example/Veco/domain/comment/repository/CommentQueryDsl.java
  src/main/java/com/example/Veco/domain/comment/repository/CommentQueryDslImpl.java
  src/main/java/com/example/Veco/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/Veco/domain/issue/repository/CustomIssueRepositoryImpl.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
  src/main/java/com/example/Veco/domain/member/entity/Member.java
  src/main/java/com/example/Veco/domain/member/service/MemberCommandService.java
  src/main/java/com/example/Veco/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/Veco/domain/workspace/controller/SettingRestController.java
  src/main/java/com/example/Veco/domain/workspace/error/SettingHandler.java
  src/main/java/com/example/Veco/domain/workspace/error/SettingSuccessCode.java
  src/main/java/com/example/Veco/global/auth/oauth2/exception/code/OAuth2ErrorCode.java
  src/main/java/com/example/Veco/global/auth/oauth2/service/OAuth2UserService.java
Labels: ♻️ Refactor, ✨Feat

#126 Fix/#123 외부 이슈 soft delete 삭제 오류 해결
  src/main/java/com/example/Veco/domain/external/controller/ExternalController.java
  src/main/java/com/example/Veco/domain/external/controller/ExternalSwaggerDocs.java
  src/main/java/com/example/Veco/domain/external/converter/ExternalConverter.java
  src/main/java/com/example/Veco/domain/external/dto/response/ExternalResponseDTO.java
  src/main/java/com/example/Veco/domain/external/entity/External.java
  src/main/java/com/example/Veco/domain/external/exception/code/ExternalErrorCode.java
  src/main/java/com/example/Veco/domain/external/repository/ExternalRepository.java
  src/main/java/com/example/Veco/domain/external/service/ExternalService.java
Labels: 🐛 Bug & Fix, ✨Feat

#128 🐛 [Fix] 탈퇴한 회원이 동일 소셜 계정으로 재가입할 때의 문제 수정
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDslImpl.java
  src/main/java/com/example/Veco/domain/comment/entity/Comment.java
  src/main/java/com/example/Veco/domain/comment/repository/CommentQueryDslImpl.java
  src/main/java/com/example/Veco/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/Veco/domain/issue/repository/CustomIssueRepositoryImpl.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
  src/main/java/com/example/Veco/domain/mapping/entity/MemberTeam.java
  src/main/java/com/example/Veco/domain/mapping/repository/MemberTeamRepository.java
  src/main/java/com/example/Veco/domain/member/entity/Member.java
  src/main/java/com/example/Veco/domain/member/service/MemberCommandServiceImpl.java
Labels: 🐛 Bug & Fix

#131 Fix:#130 외부 이슈생성해결
  src/main/java/com/example/Veco/domain/external/dto/request/ExternalRequestDTO.java
Labels: 🐛 Bug & Fix

#132 ♻️ [Refactor] 목표, 이슈 상세 조회 시 댓글 ID 추가 조회
  src/main/java/com/example/Veco/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/Veco/domain/goal/controller/GoalController.java
  src/main/java/com/example/Veco/domain/goal/converter/GoalConverter.java
  src/main/java/com/example/Veco/domain/goal/dto/response/GoalResDTO.java
  src/main/java/com/example/Veco/domain/issue/converter/IssueConverter.java
  src/main/java/com/example/Veco/domain/issue/dto/IssueResponseDTO.java
  src/main/java/com/example/Veco/domain/issue/service/IssueQueryService.java
Labels: ♻️ Refactor, ✨Feat

#146 Refactor:#145 깃허브 URL 수정
  src/main/java/com/example/Veco/domain/github/controller/GitHubRestController.java
Labels: ♻️ Refactor

#150 🐛 [Fix] 토큰 만료 시의 응답 수정
  src/main/java/com/example/Veco/global/auth/jwt/controller/JwtController.java
  src/main/java/com/example/Veco/global/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/example/Veco/global/auth/jwt/util/JwtUtil.java
  src/main/java/com/example/Veco/global/config/SecurityConfig.java
Labels: 🐛 Bug & Fix
