Repository vecosystem/VECO_Backend, pull requests merged in 2025-07, with the labels that each got.

#12 Feat/#7-member-구현
  src/main/java/com/example/Veco/domain/member/controller/MemberRestController.java
  src/main/java/com/example/Veco/domain/member/converter/MemberConverter.java
  src/main/java/com/example/Veco/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/Veco/domain/member/service/MemberCommandService.java
  src/main/java/com/example/Veco/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/Veco/domain/member/service/MemberQueryService.java
  src/main/java/com/example/Veco/domain/member/service/MemberQueryServiceImpl.java
Labels: ✨Feat

#22 Feat/#10 feat 알림 구현
  src/main/java/com/example/Veco/VecoApplication.java
  src/main/java/com/example/Veco/domain/assignee/entity/Assignee.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDsl.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDslImpl.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeRepository.java
  src/main/java/com/example/Veco/domain/external/entity/External.java
  src/main/java/com/example/Veco/domain/goal/entity/Goal.java
  src/main/java/com/example/Veco/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/Veco/domain/issue/entity/Issue.java
  src/main/java/com/example/Veco/domain/issue/repository/IssueRepository.java
  src/main/java/com/example/Veco/domain/mapping/entity/MemberTeam.java
  src/main/java/com/example/Veco/domain/mapping/repository/MemberTeamRepository.java
  src/main/java/com/example/Veco/domain/memberNotification/controller/memberNotiController.java
  src/main/java/com/example/Veco/domain/memberNotification/entity/MemberNotification.java
  src/main/java/com/example/Veco/domain/memberNotification/repository/MemberNotiQueryDsl.java
  src/main/java/com/example/Veco/domain/memberNotification/repository/MemberNotiQueryDslImpl.java
  src/main/java/com/example/Veco/domain/memberNotification/repository/MemberNotiRepository.java
  src/main/java/com/example/Veco/domain/memberNotification/service/MemberNotiCommandService.java
  src/main/java/com/example/Veco/domain/memberNotification/service/MemberNotiCommandServiceImpl.java
  src/main/java/com/example/Veco/domain/notification/controller/NotiController.java
  src/main/java/com/example/Veco/domain/notification/converter/NotiConverter.java
  src/main/java/com/example/Veco/domain/notification/dto/NotiReqDTO.java
  src/main/java/com/example/Veco/domain/notification/dto/NotiResDTO.java
  src/main/java/com/example/Veco/domain/notification/entity/Notification.java
  src/main/java/com/example/Veco/domain/notification/repository/NotiQueryDsl.java
  src/main/java/com/example/Veco/domain/notification/repository/NotiQueryDslImpl.java
  src/main/java/com/example/Veco/domain/notification/repository/NotiRepository.java
  src/main/java/com/example/Veco/domain/notification/service/NotiCommandService.java
  src/main/java/com/example/Veco/domain/notification/service/NotiQueryService.java
  src/main/java/com/example/Veco/domain/notification/service/NotiQueryServiceImpl.java
  src/main/java/com/example/Veco/domain/notification/service/NoticommandServiceImpl.java
  src/main/java/com/example/Veco/domain/notification/service/NotificationCleanUpScheduler.java
  src/main/java/com/example/Veco/domain/reminder/service/ReminderCacheService.java
  src/main/java/com/example/Veco/domain/reminder/service/ReminderScheduler.java
  src/main/java/com/example/Veco/domain/reminder/service/ReminderService.java
  src/main/java/com/example/Veco/domain/reminder/service/ReminderTargetService.java
  src/main/java/com/example/Veco/domain/reminder/util/RedisKeyUtil.java
Labels: ✨Feat

#26 Feat/#18 댓글 생성 조회 기능 구현
  src/main/java/com/example/Veco/domain/comment/controller/CommentController.java
  src/main/java/com/example/Veco/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/Veco/domain/comment/converter/CommentRoomConverter.java
  src/main/java/com/example/Veco/domain/comment/dto/request/CommentCreateDTO.java
  src/main/java/com/example/Veco/domain/comment/dto/response/CommentListResponseDTO.java
  src/main/java/com/example/Veco/domain/comment/dto/response/CommentRoomResponseDTO.java
  src/main/java/com/example/Veco/domain/comment/entity/Comment.java
  src/main/java/com/example/Veco/domain/comment/entity/CommentRoom.java
  src/main/java/com/example/Veco/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/Veco/domain/comment/service/CommentService.java
  src/main/java/com/example/Veco/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/example/Veco/domain/external/entity/External.java
  src/main/java/com/example/Veco/domain/external/exception/ExternalException.java
  src/main/java/com/example/Veco/domain/external/exception/code/ExternalErrorCode.java
  src/main/java/com/example/Veco/domain/external/repository/ExternalRepository.java
  src/main/java/com/example/Veco/domain/goal/service/query/GoalQueryService.java
  src/main/java/com/example/Veco/domain/mapping/repository/CommentRoomRepository.java
  src/main/resources/application.properties
  src/test/java/com/example/Veco/domain/comment/service/CommentServiceTest.java
Labels: ✨Feat

#41 ♻️ [Refactor] 목표 API 수정
  src/main/java/com/example/Veco/domain/assignee/converter/AssigneeConverter.java
  src/main/java/com/example/Veco/domain/goal/controller/GoalController.java
  src/main/java/com/example/Veco/domain/goal/dto/request/GoalReqDTO.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalCommandService.java
  src/main/java/com/example/Veco/domain/goal/service/command/GoalTransactionalService.java
Labels: ♻️ Refactor

#32 Feat/#24 알림 예외처리 및 필터항목 수정
  src/main/java/com/example/Veco/domain/external/repository/ExternalRepository.java
  src/main/java/com/example/Veco/domain/memberNotification/controller/memberNotiController.java
  src/main/java/com/example/Veco/domain/memberNotification/exception/MemberNotiException.java
  src/main/java/com/example/Veco/domain/memberNotification/exception/code/MemberNotiErrorCode.java
  src/main/java/com/example/Veco/domain/memberNotification/exception/code/MemberNotiSuccessCode.java
  src/main/java/com/example/Veco/domain/memberNotification/repository/MemberNotiQueryDsl.java
  src/main/java/com/example/Veco/domain/memberNotification/repository/MemberNotiQueryDslImpl.java
  src/main/java/com/example/Veco/domain/memberNotification/service/MemberNotiCommandService.java
  src/main/java/com/example/Veco/domain/memberNotification/service/MemberNotiCommandServiceImpl.java
  src/main/java/com/example/Veco/domain/notification/controller/NotiController.java
  src/main/java/com/example/Veco/domain/notification/converter/NotiConverter.java
  src/main/java/com/example/Veco/domain/notification/dto/NotiResDTO.java
  src/main/java/com/example/Veco/domain/notification/enums/FilterType.java
  src/main/java/com/example/Veco/domain/notification/exception/NotificationException.java
  src/main/java/com/example/Veco/domain/notification/exception/code/NotiErrorCode.java
  src/main/java/com/example/Veco/domain/notification/exception/code/NotiSuccessCode.java
  src/main/java/com/example/Veco/domain/notification/service/NotiQueryService.java
  src/main/java/com/example/Veco/domain/notification/service/NotiQueryServiceImpl.java
Labels: ♻️ Refactor, ✨Feat

#38 ✨ [Feat] slack 연동, 메시지 전송 기능
  build.gradle
  src/main/java/com/example/Veco/domain/external/converter/ExternalServiceConverter.java
  src/main/java/com/example/Veco/domain/external/entity/ExternalService.java
  src/main/java/com/example/Veco/domain/external/repository/ExternalServiceRepository.java
  src/main/java/com/example/Veco/domain/external/service/ExternalService.java
  src/main/java/com/example/Veco/domain/mapping/converter/LinkConverter.java
  src/main/java/com/example/Veco/domain/mapping/entity/Link.java
  src/main/java/com/example/Veco/domain/mapping/repository/LinkRepository.java
  src/main/java/com/example/Veco/domain/slack/controller/SlackController.java
  src/main/java/com/example/Veco/domain/slack/converter/SlackConverter.java
  src/main/java/com/example/Veco/domain/slack/dto/SlackResDTO.java
  src/main/java/com/example/Veco/domain/slack/exception/SlackException.java
  src/main/java/com/example/Veco/domain/slack/exception/code/SlackErrorCode.java
  src/main/java/com/example/Veco/domain/slack/exception/code/SlackSuccessCode.java
  src/main/java/com/example/Veco/domain/slack/service/SlackCommandService.java
  src/main/java/com/example/Veco/domain/slack/util/SlackUtil.java
  src/main/resources/static/slack-test.html
Labels: ✨Feat

#44 ✨ feat: 이슈 수정/삭제 API 구현
  src/main/java/com/example/Veco/domain/assignee/converter/AssigneeConverter.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDsl.java
  src/main/java/com/example/Veco/domain/assignee/repository/AssigneeQueryDslImpl.java
  src/main/java/com/example/Veco/domain/issue/controller/IssueController.java
  src/main/java/com/example/Veco/domain/issue/converter/IssueConverter.java
  src/main/java/com/example/Veco/domain/issue/dto/IssueReqDTO.java
  src/main/java/com/example/Veco/domain/issue/dto/IssueResponseDTO.java
  src/main/java/com/example/Veco/domain/issue/entity/Issue.java
  src/main/java/com/example/Veco/domain/issue/exception/code/IssueErrorCode.java
  src/main/java/com/example/Veco/domain/issue/exception/code/IssueSuccessCode.java
  src/main/java/com/example/Veco/domain/issue/service/command/IssueCommandService.java
  src/main/java/com/example/Veco/domain/issue/service/command/IssueCommandServiceImpl.java
Labels: ✨Feat
